# Generated by Django 5.1.7 on 2025-04-02 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme (kg)'), ('g', 'Gramme (g)'), ('l', 'Litre (l)'), ('ml', 'Millilitre (ml)'), ('m', 'Mètre (m)'), ('cm', 'Centimètre (cm)'), ('piece', 'Pièce'), ('autre', 'Autre')], default='piece', max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantité disponible')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (TND)')),
                ('date_achat', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name='Date de validité')),
            ],
        ),
    ]
