# Generated by Django 5.1.7 on 2025-04-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité en stock ')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Seuil d'alerte")),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ingredients.ingredient')),
            ],
            options={
                'verbose_name': 'Stock',
                'ordering': ['ingredient__nom'],
            },
        ),
    ]
