# Generated by Django 5.1.7 on 2025-04-02 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_plat', models.CharField(choices=[('petit_dejeuner', 'Petit déjeuner'), ('dejeuner', 'Déjeuner'), ('diner', 'Dîner')], max_length=20)),
                ('nombre_portions', models.PositiveIntegerField()),
                ('date_preparation', models.DateField(auto_now_add=True)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recette')),
            ],
        ),
        migrations.CreateModel(
            name='PlatIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient', verbose_name='Ingrédient')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats.plat', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Composition de plat',
                'unique_together': {('plat', 'ingredient')},
            },
        ),
    ]
