# Generated by Django 5.1.7 on 2025-04-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
        ('recettes', '0002_recette_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recettes.recette'),
        ),
    ]
