# Generated by Django 5.1.7 on 2025-04-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la recette')),
                ('description', models.TextField(blank=True)),
                ('temps_preparation', models.PositiveIntegerField(help_text='Temps en minutes', verbose_name='Temps (minutes)')),
                ('instructions', models.TextField(verbose_name='Étapes de préparation')),
            ],
        ),
        migrations.CreateModel(
            name='CompositionRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité nécessaire')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recettes.recette')),
            ],
            options={
                'unique_together': {('recette', 'ingredient')},
            },
        ),
    ]
