# Generated by Django 5.1.7 on 2025-04-02 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du menu')),
                ('date_service', models.DateField(verbose_name='Date de service')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Ordre d'affichage")),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Menu')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats.plat', verbose_name='Plat')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('menu', 'plat')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='plats',
            field=models.ManyToManyField(through='menus.MenuPlat', to='plats.plat', verbose_name='Plats composants'),
        ),
    ]
